### PR TITLE
Rating system for closed cases

### PR DESCRIPTION
**Pull request by Emil8250**
Fix to https://github.com/KarlOfDuty/SupportBoi/issues/12

new columns have been added, tables might have to be recreated.

### CODE REVIEW

**Comment by KarlOfDuty** [comment]
I think this would need some more features to be worth changing the database structure for. I was thinking of commands to show stats like ratings over specific periods and showing the top rated staff members and such.

**Comment by Emil8250** [comment]
Ahh okay great - will do some changes to the rating system then, normalizing it on the database level, and implementing further features

**Comment by KarlOfDuty** [comment]
Sounds good.

**Comment by thedovy** [comment]
@Emil8250 Can you please add support for custom colors? Thanks!

**Comment by KarlOfDuty** [comment]
Closed due to inactivity.

**Pull request closed without merging**
